from typing import TypedDict, List, Dict, Any

class GraphState(TypedDict):
    srs_input: str           #input 
    microservices: List[Dict] #list of microservices
    backend_plan: str       #backend plan
    frontend_plan: str       #frontend plan
    generated_images: List[str] #list of generated images
    frontend_spec: Dict[str, Any]  # Frontend spec generated by Architect
    frontend_code: str       #frontend code
    user_feedback: str       #user feedback
    is_approved: bool        #user approval
    backend_code:Dict[str, str] #backend code
    

