import JSZip from 'jszip';
import { readProjectFiles, renderGeneratedEnv } from '@/lib/workspace/fs';
import { connectDB } from '@/lib/db/mongoose';
import { Project } from '@/lib/db/models/Project';
import { slugify } from '@/lib/utils';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function runInstructions(name: string): string {
  return [
    `# ${name}`,
    '',
    'Generated by **AI Web Builder**.',
    '',
    '## Run locally',
    '',
    '```bash',
    'npm install',
    'npm run dev',
    '```',
    '',
    'Then open http://localhost:3000',
    '',
    '## Database',
    '',
    'The MongoDB connection string is already set in `.env.local` (`MONGODB_URI`).',
    'It points at your Atlas cluster with a database name dedicated to this app.',
    '',
  ].join('\n');
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;

  const files = await readProjectFiles(id);
  if (files.length === 0) {
    return new Response('No generated files for this project', { status: 404 });
  }

  let name = id;
  let dbName = 'app';
  try {
    await connectDB();
    const project = await Project.findById(id).lean();
    if (project) {
      name = (project.name as string) || id;
      dbName = (project.dbName as string) || 'app';
    }
  } catch {
    // metadata is optional for export
  }

  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  // Inject the live DB connection + a run guide that were not part of the model output.
  zip.file('.env.local', renderGeneratedEnv(dbName));
  zip.file('RUN.md', runInstructions(name));

  const data = await zip.generateAsync({ type: 'uint8array' });

  // Cast around the @types/node 22 / TS 5.7 ArrayBufferLike-vs-ArrayBuffer
  // generic mismatch; the value is a valid byte stream at runtime.
  return new Response(data as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${slugify(name)}.zip"`,
      'Cache-Control': 'no-store',
    },
  });
}
