#!/usr/bin/env python3
r"""
rebrand_dyad.py  -  Automated, SAFE migration of open-source Dyad -> "AI Design App".

What it does (100% automated):
  1. Backs up your destination folder to a timestamped .zip (reversible).
  2. Wipes the destination (keeping its .git so you don't lose version history).
  3. Copies ALL of Dyad's source into the destination (skips node_modules / build / .git).
  4. Rebrands Dyad -> AI Design App, case-sensitively, KEEPING THE CODE COMPILABLE:
        - in code   : Dyad->AiDesignApp   dyad->aidesignapp   DYAD->AI_DESIGN_APP   (no spaces!)
        - in docs   : Dyad->"AI Design App"  dyad->ai-design-app  DYAD->AI_DESIGN_APP
        - product   : package.json name/productName set so the window/installer reads "AI Design App"
     LICENSE / NOTICE / CLA are copied VERBATIM (Apache-2.0 attribution stays intact).
  5. Prints a clean log of files copied / modified / kept / skipped.

Usage (Windows PowerShell or CMD):
    python rebrand_dyad.py --dst "D:\GITHUB\ai-design-app"
    python rebrand_dyad.py --src "D:\GITHUB\dyad" --dst "D:\GITHUB\ai-design-app" --yes

After it finishes:
    cd "D:\GITHUB\ai-design-app"
    npm install
    npm start        (or whatever Dyad's README says)
"""
import argparse
import json
import os
import shutil
import sys
import zipfile
from datetime import datetime

SRC_DEFAULT = r"D:\GITHUB\dyad"

# never copied (transient / huge / regenerated by install+build, or your own VCS)
EXCLUDE_DIRS = {
    "node_modules", ".git", "dist", "dist-electron", "out", "build", ".next", "release",
    "coverage", ".turbo", ".cache", ".vite", "__pycache__", ".venv", "playwright-report",
    ".idea", ".vscode-test",
}
# legal / attribution files -> copied BYTE-FOR-BYTE (Apache-2.0 requires this)
KEEP_VERBATIM = {"license", "license.md", "license.txt", "notice", "notice.md",
                 "copying", "cla.md", "authors"}

DOC_EXT = {".md", ".mdx", ".txt", ".html", ".htm"}
BINARY_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".icns", ".bmp", ".woff", ".woff2",
    ".ttf", ".otf", ".eot", ".mp4", ".webm", ".mov", ".mp3", ".wav", ".pdf", ".zip", ".gz",
    ".tar", ".7z", ".node", ".exe", ".dll", ".dylib", ".so", ".wasm", ".lockb", ".bin",
    ".db", ".sqlite", ".sqlite3", ".pyc", ".class", ".jar", ".keystore",
}

# CODE = identifier-safe (NO spaces, so JS/TS still compiles).  DOC = human-readable.
CODE_REPLACE = [("DYAD", "AI_DESIGN_APP"), ("Dyad", "AiDesignApp"), ("dyad", "aidesignapp")]
DOC_REPLACE = [("DYAD", "AI_DESIGN_APP"), ("Dyad", "AI Design App"), ("dyad", "ai-design-app")]
PRODUCT_NAME = "AI Design App"      # shown in the app window / installer
PKG_NAME = "ai-design-app"          # package.json "name"


def apply_table(text, table):
    n = 0
    for a, b in table:
        if a in text:
            n += text.count(a)
            text = text.replace(a, b)
    return text, n


def rename_name(name):
    # file / folder names are always code-safe (no spaces in paths)
    for a, b in CODE_REPLACE:
        name = name.replace(a, b)
    return name


def looks_binary(path):
    if os.path.splitext(path)[1].lower() in BINARY_EXT:
        return True
    try:
        with open(path, "rb") as f:
            return b"\x00" in f.read(8192)
    except OSError:
        return True


def make_backup(dst):
    if not os.path.isdir(dst) or not os.listdir(dst):
        return None
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_path = os.path.join(os.path.dirname(os.path.abspath(dst)),
                            f"{os.path.basename(os.path.abspath(dst))}_backup_{stamp}.zip")
    print(f"[backup] zipping current destination -> {zip_path}")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for root, dirs, files in os.walk(dst):
            dirs[:] = [d for d in dirs if d not in {"node_modules", ".git"}]  # keep the zip small
            for fn in files:
                fp = os.path.join(root, fn)
                z.write(fp, os.path.relpath(fp, dst))
    return zip_path


def clear_destination(dst):
    if not os.path.isdir(dst):
        os.makedirs(dst, exist_ok=True)
        return
    for entry in os.listdir(dst):
        if entry == ".git":          # keep YOUR version history
            continue
        p = os.path.join(dst, entry)
        shutil.rmtree(p, ignore_errors=True) if os.path.isdir(p) else os.remove(p)


def migrate(src, dst):
    copied = modified = kept = skipped = 0
    pro_seen = False
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        rel_dir = os.path.relpath(root, src)
        if rel_dir.replace("\\", "/").startswith("src/pro"):
            pro_seen = True
        for fn in files:
            src_path = os.path.join(root, fn)
            rel = os.path.relpath(src_path, src)
            dst_rel = os.path.join(*[rename_name(part) for part in rel.split(os.sep)])
            dst_path = os.path.join(dst, dst_rel)
            os.makedirs(os.path.dirname(dst_path), exist_ok=True)

            low = fn.lower()
            if low in KEEP_VERBATIM:                 # legal files -> verbatim
                shutil.copy2(src_path, dst_path); copied += 1; kept += 1; continue
            if looks_binary(src_path):               # images/fonts/etc -> verbatim
                shutil.copy2(src_path, dst_path); copied += 1; skipped += 1; continue

            try:
                with open(src_path, "r", encoding="utf-8", errors="replace") as f:
                    text = f.read()
            except OSError:
                shutil.copy2(src_path, dst_path); copied += 1; skipped += 1; continue

            table = DOC_REPLACE if os.path.splitext(fn)[1].lower() in DOC_EXT else CODE_REPLACE
            new_text, hits = apply_table(text, table)
            with open(dst_path, "w", encoding="utf-8", newline="") as f:
                f.write(new_text)
            copied += 1
            modified += 1 if hits else 0
    return copied, modified, kept, skipped, pro_seen


def fix_package_json(dst):
    pkg = os.path.join(dst, "package.json")
    if not os.path.isfile(pkg):
        return
    try:
        with open(pkg, "r", encoding="utf-8") as f:
            data = json.load(f)
        data["name"] = PKG_NAME
        data["productName"] = PRODUCT_NAME
        if isinstance(data.get("build"), dict):
            data["build"]["productName"] = PRODUCT_NAME
        with open(pkg, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print('[fix] package.json -> name="ai-design-app", productName="AI Design App"')
    except (OSError, ValueError) as e:
        print(f"[warn] could not patch package.json: {e}")


def main():
    ap = argparse.ArgumentParser(description="Automated Dyad -> AI Design App rebrand")
    ap.add_argument("--src", default=SRC_DEFAULT, help="Dyad source folder")
    ap.add_argument("--dst", required=True, help="your AI Design App destination folder")
    ap.add_argument("--yes", action="store_true", help="skip the confirmation prompt")
    a = ap.parse_args()

    src, dst = os.path.abspath(a.src), os.path.abspath(a.dst)
    if not os.path.isdir(src) or not os.path.isfile(os.path.join(src, "package.json")):
        sys.exit(f"[abort] source is not a valid Dyad project: {src}")
    if src == dst:
        sys.exit("[abort] source and destination are the same folder")
    s, d = src.lower().rstrip("\\/") + "\\", dst.lower().rstrip("\\/") + "\\"
    if s.startswith(d) or d.startswith(s):
        sys.exit("[abort] source and destination must not be nested inside each other")

    print("=" * 64)
    print(f"  SOURCE (Dyad)      : {src}")
    print(f"  DESTINATION (wipe) : {dst}")
    print("  NOTE: src/pro/ is under a SEPARATE non-Apache license - review")
    print("        src/pro/LICENSE before you redistribute the result.")
    print("=" * 64)
    if not a.yes:
        if input('Type "YES" to back up + wipe the destination and migrate: ').strip() != "YES":
            sys.exit("[abort] cancelled")

    backup = make_backup(dst)
    clear_destination(dst)
    copied, modified, kept, skipped, pro_seen = migrate(src, dst)
    fix_package_json(dst)

    print("\n" + "=" * 64)
    print("  MIGRATION COMPLETE")
    print(f"  files copied        : {copied}")
    print(f"  files rebranded     : {modified}")
    print(f"  legal kept verbatim : {kept}  (LICENSE / NOTICE / CLA)")
    print(f"  binaries copied     : {skipped}")
    if backup:
        print(f"  backup of old app   : {backup}")
    if pro_seen:
        print("  [!] src/pro/ was copied - it is NOT Apache-2.0; check its license.")
    print("=" * 64)
    print('Next:  cd "%s"  &&  npm install  &&  npm start' % dst)


if __name__ == "__main__":
    main()
