import React, { useEffect, useState } from "react";
import { Icon } from "../core/ui";

export const PHASE = {
  INTAKE: "intake",
  ANALYZING: "analyzing",
  QUESTIONING: "questioning",
  PREPARING: "preparing",
  GENERATING: "generating",
  SRS: "srs",
};

const SAMPLE_SRS = {
  title: "Software Requirements Specification",
  version: "v1.0 - Generated by Agent 1",
  sections: [
    {
      heading: "1. Project Overview",
      body:
        "A guided project intake workflow where users describe an idea, answer friendly requirement questions, and receive a structured SRS in JSON and PDF.",
    },
    {
      heading: "2. Target Users",
      body:
        "Primary users include founders, business teams, and non-technical product owners who need a clear software specification.",
    },
    {
      heading: "3. Core Features",
      body:
        "Multimodal intake, AI-guided question flow, requirement validation, SRS generation, PDF export, and review dashboard.",
    },
  ],
};

function ProgressStagePanel({ label, statuses, duration = 5, color = "#1f6feb", onComplete }) {
  const [progress, setProgress] = useState(0);
  const [statusIndex, setStatusIndex] = useState(0);

  useEffect(() => {
    const tickCount = duration * 10;
    const progressInterval = setInterval(() => {
      setProgress((current) => {
        const next = current + 100 / tickCount;
        if (next >= 100) {
          clearInterval(progressInterval);
          setTimeout(() => onComplete?.(), 300);
          return 100;
        }
        return next;
      });
    }, 100);

    const statusInterval = setInterval(() => {
      setStatusIndex((current) => Math.min(current + 1, statuses.length - 1));
    }, (duration * 1000) / Math.max(statuses.length, 1));

    return () => {
      clearInterval(progressInterval);
      clearInterval(statusInterval);
    };
  }, [color, duration, onComplete, statuses]);

  return (
    <div className="flex w-full max-w-md flex-col items-center gap-4">
      <div className="relative flex min-h-[140px] items-center justify-center">
        <Icon name="Loader2" size={140} className="animate-spin text-[#1f6feb]" />
      </div>
      <p className="text-sm font-medium text-gray-800">{label}</p>
      <p className="min-h-4 text-xs text-gray-500">{statuses[statusIndex]}</p>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-gray-200">
        <div
          className="h-full rounded-full transition-all duration-100"
          style={{ width: `${progress}%`, background: color }}
        />
      </div>
      <p className="text-xs font-mono" style={{ color }}>
        {Math.round(progress)}%
      </p>
    </div>
  );
}

function ChatBubble({ text, isAgent = true, delay = 0 }) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), delay);
    return () => clearTimeout(timer);
  }, [delay]);

  if (!visible) {
    return null;
  }

  return (
    <div
      className={`flex gap-3 ${isAgent ? "justify-start" : "justify-end"}`}
      style={{ animation: "slideInUp 0.35s ease forwards" }}
    >
      {isAgent ? (
        <div className="mt-1 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-[#1f6feb]">
          <Icon name="Zap" size={12} className="text-white" />
        </div>
      ) : null}
      <div
        className={`max-w-[38rem] rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
          isAgent
            ? "rounded-tl-sm border border-gray-200 bg-white text-gray-800 shadow-sm"
            : "rounded-tr-sm bg-[#1f6feb] text-white"
        }`}
      >
        {text}
      </div>
    </div>
  );
}

function hasAnswerValue(value) {
  return Array.isArray(value) ? value.length > 0 : Boolean(String(value || "").trim());
}

function formatAnswerText(value) {
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  return String(value || "").trim();
}

function normalizeDraftValue(question, value) {
  if (!question) {
    return "";
  }
  if (question.inputType === "multiselect") {
    return Array.isArray(value) ? value : [];
  }
  return value || "";
}

function QuestionComposer({ question, value, onChange, onSubmit }) {
  const normalizedValue = normalizeDraftValue(question, value);
  const hasValue = hasAnswerValue(normalizedValue);

  if (!question) {
    return null;
  }

  if (question.inputType === "select" || question.inputType === "multiselect") {
    const selectedValues = Array.isArray(normalizedValue) ? normalizedValue : [normalizedValue].filter(Boolean);

    return (
      <div
        className="ml-10 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"
        style={{ animation: "fadeIn 0.3s ease both" }}
      >
        <div className="flex flex-wrap gap-2">
          {(question.options || []).map((option) => {
            const active = selectedValues.includes(option);
            return (
              <button
                key={option}
                type="button"
                onClick={() => {
                  if (question.inputType === "multiselect") {
                    onChange(
                      active ? selectedValues.filter((item) => item !== option) : [...selectedValues, option]
                    );
                    return;
                  }
                  onChange(option);
                }}
                className={`rounded-xl border px-3 py-2 text-xs font-medium transition-all ${
                  active
                    ? "border-[#1f6feb] bg-blue-50 text-[#1f6feb]"
                    : "border-gray-200 bg-white text-gray-600 hover:border-[#1f6feb] hover:bg-blue-50 hover:text-[#1f6feb]"
                }`}
              >
                {option}
              </button>
            );
          })}
        </div>

        <div className="mt-4 flex items-center justify-end">
          <button
            type="button"
            onClick={() => onSubmit(normalizedValue)}
            disabled={!hasValue}
            className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-semibold transition-all ${
              hasValue
                ? "bg-[#1f6feb] text-white shadow-[0_10px_28px_-14px_rgba(31,111,235,0.75)]"
                : "bg-gray-100 text-gray-400"
            }`}
          >
            <Icon name="Send" size={13} />
            Save Answer
          </button>
        </div>
      </div>
    );
  }

  const isLongForm = question.inputType === "textarea";

  return (
    <div
      className="ml-10 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"
      style={{ animation: "fadeIn 0.3s ease both" }}
    >
      {isLongForm ? (
        <textarea
          value={normalizedValue}
          onChange={(event) => onChange(event.target.value)}
          placeholder={question.placeholder || "Write your answer..."}
          rows={5}
          className="w-full resize-none rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-700 placeholder-gray-400 focus:border-[#1f6feb] focus:bg-white focus:outline-none"
        />
      ) : (
        <input
          value={normalizedValue}
          onChange={(event) => onChange(event.target.value)}
          placeholder={question.placeholder || "Write your answer..."}
          className="w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-700 placeholder-gray-400 focus:border-[#1f6feb] focus:bg-white focus:outline-none"
        />
      )}

      <div className="mt-4 flex items-center justify-end">
        <button
          type="button"
          onClick={() => onSubmit(normalizedValue)}
          disabled={!hasValue}
          className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-semibold transition-all ${
            hasValue
              ? "bg-[#1f6feb] text-white shadow-[0_10px_28px_-14px_rgba(31,111,235,0.75)]"
              : "bg-gray-100 text-gray-400"
          }`}
        >
          <Icon name="Send" size={13} />
          Save Answer
        </button>
      </div>
    </div>
  );
}

function SrsDocumentPanel({ onContinue }) {
  useEffect(() => {
    const timer = setTimeout(() => onContinue?.(), 5000);
    return () => clearTimeout(timer);
  }, [onContinue]);

  return (
    <div className="w-full max-w-2xl">
      <div className="mb-4 flex items-center gap-3 rounded-xl border border-blue-200 bg-blue-50 p-3">
        <Icon name="CheckCircle2" size={16} className="text-[#1f6feb]" />
        <p className="text-xs font-medium text-blue-700">
          SRS generated successfully. Preparing the next handoff...
        </p>
      </div>

      <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
        <div className="flex items-center justify-between border-b border-gray-200 bg-gray-50 px-5 py-4">
          <div>
            <p className="text-sm font-bold text-gray-800">{SAMPLE_SRS.title}</p>
            <p className="mt-0.5 text-xs text-gray-500">{SAMPLE_SRS.version}</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 animate-pulse rounded-full bg-[#1f6feb]" />
            <span className="text-xs text-[#1f6feb]">Ready</span>
          </div>
        </div>

        <div className="max-h-80 space-y-4 overflow-y-auto p-5">
          {SAMPLE_SRS.sections.map((section, index) => (
            <div key={section.heading} style={{ animation: `fadeIn 0.4s ease ${index * 0.15}s both` }}>
              <p className="mb-1.5 text-xs font-semibold text-[#1f6feb]">{section.heading}</p>
              <p className="text-xs leading-relaxed text-gray-600 whitespace-pre-line">{section.body}</p>
              {index < SAMPLE_SRS.sections.length - 1 ? <div className="mt-3 border-b border-gray-200" /> : null}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function AiLoadingOverlay({ title, subtitle }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-white/55 px-6 backdrop-blur-md">
      <div className="w-full max-w-xl rounded-[32px] border border-white/70 bg-white/85 p-8 text-center shadow-[0_30px_120px_-40px_rgba(31,111,235,0.45)]">
        <div className="flex justify-center">
          <img
            src="/agent1-loading.gif"
            alt="AI loading"
            className="h-56 w-auto max-w-full object-contain"
          />
        </div>
        <p className="mt-4 text-lg font-semibold text-gray-900">{title}</p>
        {subtitle ? <p className="mt-2 text-sm leading-relaxed text-gray-500">{subtitle}</p> : null}
      </div>
    </div>
  );
}

export function IdeaIntakeStage({
  idea,
  onIdeaChange,
  onCreate,
  onOpenAudio,
  onOpenImage,
  onOpenPdf,
  isRecording = false,
  files = [],
  transcript = "",
  onRemoveFile,
  isSubmitting = false,
}) {
  return (
    <div className="flex flex-1 flex-col items-center justify-center p-8" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <div className="w-full max-w-3xl">
        <div className="mb-8 flex items-center justify-center gap-3">
          <img src="/logo.png" alt="AgentForge Studio logo" className="h-11 w-auto object-contain" />
          <div>
            <p className="text-sm font-bold text-gray-800">AgentForge Studio</p>
            <p className="text-xs text-gray-500">New Project Intake</p>
          </div>
        </div>

        <h1 className="mb-2 text-center text-3xl font-bold text-gray-800">What do you want to build?</h1>
        <p className="mb-8 text-center text-sm text-gray-500">
          Describe your software idea in one input. Add audio, photo, or PDF from the icons inside the input bar.
        </p>

        <div className="overflow-hidden rounded-[28px] border border-gray-300 bg-white shadow-[0_20px_80px_-40px_rgba(31,111,235,0.35)]">
          <textarea
            value={idea}
            onChange={(event) => onIdeaChange(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter" && event.metaKey) {
                onCreate();
              }
            }}
            placeholder="e.g. A hotel booking platform where guests can search rooms, make bookings, pay online, and hotel admins can manage inventory and view revenue reports..."
            rows={6}
            className="w-full resize-none bg-white px-5 pb-4 pt-5 text-sm leading-relaxed text-gray-800 placeholder-gray-400 focus:outline-none"
            style={{ boxShadow: idea ? "inset 0 0 0 1px #1f6feb20" : "none" }}
          />

          {(files.length > 0 || transcript) ? (
            <div className="space-y-2 px-5 pb-3">
              {transcript ? (
                <div className="rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-xs text-blue-800">
                  Voice transcript: {transcript}
                </div>
              ) : null}

              {files.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {files.map((file, index) => (
                    <button
                      key={`${file.name}-${index}`}
                      type="button"
                      onClick={() => onRemoveFile?.(index)}
                      className="inline-flex items-center gap-2 rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs text-gray-600"
                    >
                      <Icon
                        name={
                          file.type?.startsWith("image/")
                            ? "Camera"
                            : file.name?.toLowerCase().endsWith(".pdf")
                              ? "FileText"
                              : "File"
                        }
                        size={12}
                      />
                      <span>{file.name}</span>
                      <Icon name="X" size={12} />
                    </button>
                  ))}
                </div>
              ) : null}
            </div>
          ) : null}

          <div className="flex items-center justify-between gap-3 border-t border-gray-200 bg-gray-50 px-4 py-3">
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onOpenAudio}
                className={`flex h-9 w-9 items-center justify-center rounded-full border transition-colors ${
                  isRecording
                    ? "border-[#1f6feb] bg-blue-50 text-[#1f6feb]"
                    : "border-gray-200 bg-white text-gray-500 hover:border-gray-300"
                }`}
                title={isRecording ? "Stop audio recording" : "Add audio"}
              >
                <Icon name={isRecording ? "Pause" : "Mic"} size={14} />
              </button>

              <button
                type="button"
                onClick={onOpenImage}
                className="flex h-9 w-9 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-500 transition-colors hover:border-gray-300"
                title="Add photo"
              >
                <Icon name="Camera" size={14} />
              </button>

              <button
                type="button"
                onClick={onOpenPdf}
                className="flex h-9 w-9 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-500 transition-colors hover:border-gray-300"
                title="Add PDF"
              >
                <Icon name="FileText" size={14} />
              </button>
            </div>

            <div className="flex items-center gap-3">
              <div className="hidden text-[10px] text-gray-400 sm:block">Cmd + Enter to create</div>
              <button
                onClick={onCreate}
                disabled={isSubmitting || (!idea.trim() && files.length === 0 && !transcript.trim())}
                className="flex h-11 w-11 items-center justify-center rounded-full transition-all duration-200"
                style={{
                  background: !isSubmitting && (idea.trim() || files.length > 0 || transcript.trim()) ? "#1f6feb" : "#e5e7eb",
                  color: !isSubmitting && (idea.trim() || files.length > 0 || transcript.trim()) ? "white" : "#9ca3af",
                  cursor: !isSubmitting && (idea.trim() || files.length > 0 || transcript.trim()) ? "pointer" : "not-allowed",
                  boxShadow: !isSubmitting && (idea.trim() || files.length > 0 || transcript.trim()) ? "0 8px 28px #1f6feb40" : "none",
                }}
                title="Create Project with AI Agents"
              >
                <Icon name={isSubmitting ? "Loader2" : "Send"} size={16} className={isSubmitting ? "animate-spin" : ""} />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function AnalysisStage({ idea, onComplete }) {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <div className="mb-2 text-center">
        <p className="mb-2 text-xs text-gray-400">Reading your idea:</p>
        <p className="max-w-sm text-sm italic text-gray-600">
          "{idea.length > 100 ? `${idea.slice(0, 100)}...` : idea}"
        </p>
      </div>
      <ProgressStagePanel
        label="Agent 1 is analyzing your idea..."
        duration={5}
        color="#1f6feb"
        statuses={[
          "Reading your idea...",
          "Understanding the product scope...",
          "Finding missing requirement details...",
          "Preparing friendly interview questions...",
        ]}
        onComplete={onComplete}
      />
    </div>
  );
}

export function QuestioningStage({
  chatRef,
  questions = [],
  currentQ = 0,
  answers = {},
  draftAnswer,
  onDraftAnswerChange,
  onAnswer,
  analysisSummary = "",
  onReset,
  onGenerate,
  isGenerating = false,
  canGenerate = false,
}) {
  const totalQuestions = questions.length;
  const answeredQuestions = questions.filter((question) => hasAnswerValue(answers[question.key])).length;
  const remainingQuestions = Math.max(totalQuestions - answeredQuestions, 0);
  const activeQuestion = currentQ < totalQuestions ? questions[currentQ] : null;

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      <div className="flex items-center justify-between gap-4 border-b border-gray-200 bg-white/80 px-5 py-4 backdrop-blur flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="h-2 w-2 rounded-full bg-[#1f6feb] animate-pulse" />
          <div>
            <p className="text-xs font-semibold text-gray-700">Agent 1 - IEEE Requirement Gathering</p>
            <p className="text-[11px] text-gray-400">Short, user-friendly questions. No technical knowledge needed.</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">
            {Math.min(answeredQuestions + (activeQuestion ? 1 : 0), totalQuestions || 1)} / {totalQuestions || 0} questions
          </span>
          <div className="h-1 w-24 overflow-hidden rounded-full bg-gray-200">
            <div
              className="h-full rounded-full bg-[#1f6feb] transition-all duration-500"
              style={{ width: `${totalQuestions ? (answeredQuestions / totalQuestions) * 100 : 0}%` }}
            />
          </div>
        </div>
      </div>

      <div ref={chatRef} className="flex-1 overflow-y-auto space-y-4 bg-[linear-gradient(180deg,#f8fbff_0%,#ffffff_28%,#ffffff_100%)] px-6 py-6">
        <ChatBubble
          delay={0}
          text={
            analysisSummary
              ? `${analysisSummary} No technical knowledge is needed. I will ask ${totalQuestions || 0} short questions so I can complete the missing SRS details.`
              : `I reviewed your project context. No technical knowledge is needed. I will ask ${totalQuestions || 0} short questions so I can complete the SRS clearly.`
          }
        />

        {questions.map((question, index) => {
          const answerValue = answers[question.key];
          const isAnswered = hasAnswerValue(answerValue);
          const isCurrent = index === currentQ && !isAnswered;
          const showQuestion = isAnswered || isCurrent || index < currentQ;

          if (!showQuestion) {
            return null;
          }

          return (
            <div key={question.key} className="space-y-3">
              <div className="flex gap-3" style={{ animation: "slideInUp 0.35s ease forwards" }}>
                <div className="mt-1 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-[#1f6feb]">
                  <Icon name="Zap" size={12} className="text-white" />
                </div>
                <div className="max-w-[38rem] rounded-2xl rounded-tl-sm border border-gray-200 bg-white px-4 py-3 shadow-sm">
                  <p className="mb-1 text-[10px] uppercase tracking-[0.16em] text-gray-400">
                    Question {index + 1} of {totalQuestions}
                  </p>
                  <p className="text-sm leading-relaxed text-gray-800">{question.question}</p>
                </div>
              </div>

              {isAnswered ? <ChatBubble text={formatAnswerText(answerValue)} isAgent={false} /> : null}

              {isCurrent ? (
                <QuestionComposer
                  question={question}
                  value={draftAnswer}
                  onChange={onDraftAnswerChange}
                  onSubmit={onAnswer}
                />
              ) : null}
            </div>
          );
        })}

        {!activeQuestion && totalQuestions > 0 ? (
          <ChatBubble text="Thanks. I now have the answers I need from this interview. Click Build App when you are ready." />
        ) : null}
      </div>

      <div className="flex items-center justify-between gap-3 border-t border-gray-200 bg-white px-5 py-4 flex-shrink-0">
        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-2 rounded-full border border-gray-200 px-4 py-2 text-xs font-medium text-gray-600 transition-colors hover:border-gray-300 hover:text-gray-900"
        >
          <Icon name="RotateCcw" size={13} />
          Reset
        </button>

        <button
          type="button"
          onClick={onGenerate}
          disabled={isGenerating || !canGenerate}
          className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-semibold transition-all ${
            isGenerating || !canGenerate
              ? "bg-gray-100 text-gray-400"
              : "bg-[#1f6feb] text-white shadow-[0_10px_28px_-14px_rgba(31,111,235,0.75)]"
          }`}
        >
          <Icon name="FileOutput" size={13} />
          {isGenerating ? "Building..." : "Build App"}
        </button>
      </div>

      {!canGenerate && totalQuestions > 0 ? (
        <div className="border-t border-gray-100 bg-gray-50 px-5 py-3 text-xs text-gray-500">
          {remainingQuestions} more answer{remainingQuestions === 1 ? "" : "s"} needed before Build App can start.
        </div>
      ) : null}
    </div>
  );
}

export function PreparingStage({ onComplete }) {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <ProgressStagePanel
        label="Processing your answers..."
        duration={4}
        color="#1f6feb"
        statuses={[
          "Organizing your answers...",
          "Filling the IEEE SRS structure...",
          "Checking for missing details...",
          "Preparing the final document...",
        ]}
        onComplete={onComplete}
      />
    </div>
  );
}

export function GeneratingStage({ onComplete }) {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <ProgressStagePanel
        label="Generating Software Requirements Specification..."
        duration={10}
        color="#1f6feb"
        statuses={[
          "Writing the SRS introduction...",
          "Building functional requirements...",
          "Adding non-functional requirements...",
          "Preparing diagrams and exports...",
          "Validating the final document...",
        ]}
        onComplete={onComplete}
      />
      <p className="max-w-xs text-center text-xs text-gray-500">
        Agent 1 is turning the interview into a complete SRS with clear requirements and export artifacts.
      </p>
    </div>
  );
}

export function GeneratedSrsStage({ onContinue }) {
  return (
    <div className="flex flex-1 flex-col items-center justify-start overflow-y-auto px-6 pt-8" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <SrsDocumentPanel onContinue={onContinue} />
    </div>
  );
}
