import React, { useEffect, useState } from "react";
import { Icon } from "../core/ui";

export const PHASE = {
  INTAKE: "intake",
  ANALYZING: "analyzing",
  QUESTIONING: "questioning",
  PREPARING: "preparing",
  GENERATING: "generating",
  SRS: "srs",
};

const QUESTIONS = [
  {
    id: "q1",
    text: "What type of application do you want to build?",
    options: ["Web Application", "Mobile App", "Desktop App", "API Platform", "Full Stack SaaS"],
  },
  {
    id: "q2",
    text: "Who are the primary users of your app?",
    options: [
      "General Public / Consumers",
      "Business Users (B2B)",
      "Internal Team / Employees",
      "Developers / Technical Users",
    ],
  },
  {
    id: "q3",
    text: "What best describes the core domain?",
    options: [
      "E-commerce / Marketplace",
      "Healthcare / Medical",
      "Education / LMS",
      "Hospitality / Booking",
      "Finance / Fintech",
      "Logistics / Operations",
    ],
  },
  {
    id: "q4",
    text: "What key features must your app include?",
    options: [
      "User auth + profiles",
      "Booking / scheduling",
      "Payments & checkout",
      "Admin dashboard + reports",
      "Real-time notifications",
      "Multi-role access control",
    ],
  },
  {
    id: "q5",
    text: "How many users do you expect at launch?",
    options: ["< 100 (internal/prototype)", "100 - 1,000", "1,000 - 10,000", "10,000+ (scale from day 1)"],
  },
  {
    id: "q6",
    text: "Which frontend stack do you prefer?",
    options: ["React + Tailwind CSS", "Next.js (SSR)", "Vue.js", "Flutter Web", "Let Agent Decide"],
  },
  {
    id: "q7",
    text: "Which backend stack do you prefer?",
    options: ["FastAPI (Python)", "Node.js / Express", "NestJS", "Spring Boot (Java)", "Let Agent Decide"],
  },
  {
    id: "q8",
    text: "What database fits your needs?",
    options: ["PostgreSQL (relational)", "MongoDB (document)", "MySQL", "Supabase (managed)", "Let Agent Decide"],
  },
  {
    id: "q9",
    text: "Where do you plan to deploy?",
    options: ["AWS (ECS + RDS)", "Vercel + Supabase", "Docker / Self-hosted", "Google Cloud", "Let Agent Decide"],
  },
  {
    id: "q10",
    text: "What is your development timeline?",
    options: ["ASAP / Prototype now", "1 month sprint", "2-3 months", "6+ months (full build)"],
  },
];

const SAMPLE_SRS = {
  title: "Software Requirements Specification",
  version: "v1.0 - Generated by Agent 1",
  sections: [
    {
      heading: "1. Project Overview",
      body:
        "A modern hotel booking platform enabling guests to search, compare, and reserve rooms online. The system supports real-time availability, secure payments via Stripe, guest profile management, and an admin dashboard for hotel operators to manage inventory, pricing, and analytics.",
    },
    {
      heading: "2. Target Users",
      body:
        "- Hotel Guests: browse rooms, make bookings, manage reservations\n- Hotel Admins: manage rooms, pricing, occupancy reports\n- System Admin: platform configuration, integrations, user management",
    },
    {
      heading: "3. Core Features",
      body:
        "- Room search with filters (date, type, capacity, price)\n- Secure checkout with Stripe payment integration\n- Booking management (create, modify, cancel)\n- Email and SMS confirmation notifications\n- Admin dashboard with occupancy and revenue charts\n- Role-based access control (Guest / Admin)",
    },
    {
      heading: "4. Technical Architecture",
      body:
        "Frontend: React + Tailwind CSS. Backend: FastAPI (Python). Database: PostgreSQL. Auth: JWT + OAuth2. Deployment: AWS ECS + RDS. Architecture: Modular Monolith.",
    },
    {
      heading: "5. Non-Functional Requirements",
      body:
        "Performance: < 2s page load (P95). Availability: 99.5% uptime SLA. Security: PCI-DSS compliant payment flow, GDPR-ready. Scalability: Containerized services with horizontal scaling via ECS.",
    },
    {
      heading: "6. Estimated Timeline",
      body:
        "Phase 1 (2 weeks): Auth + Room catalog + Booking flow\nPhase 2 (2 weeks): Payments + Notifications + Admin panel\nPhase 3 (1 week): QA + DevOps + Deployment preparation",
    },
  ],
};

function ProgressStagePanel({ label, statuses, duration = 5, color = "#1f6feb", onComplete }) {
  const [progress, setProgress] = useState(0);
  const [statusIndex, setStatusIndex] = useState(0);

  useEffect(() => {
    const tickCount = duration * 10;
    const progressInterval = setInterval(() => {
      setProgress((current) => {
        const next = current + 100 / tickCount;
        if (next >= 100) {
          clearInterval(progressInterval);
          setTimeout(() => onComplete?.(), 300);
          return 100;
        }
        return next;
      });
    }, 100);

    const statusInterval = setInterval(() => {
      setStatusIndex((current) => Math.min(current + 1, statuses.length - 1));
    }, (duration * 1000) / statuses.length);

    return () => {
      clearInterval(progressInterval);
      clearInterval(statusInterval);
    };
  }, [color, duration, onComplete, statuses]);

  return (
    <div className="flex flex-col items-center gap-4 w-full max-w-md">
      <div className="min-h-[140px] flex items-center justify-center relative">
        <Icon name="Loader2" size={140} />
      </div>
      <p className="text-sm font-medium text-gray-800">{label}</p>
      <p className="text-xs text-gray-500 min-h-4 transition-all">{statuses[statusIndex]}</p>
      <div className="w-full bg-gray-200 rounded-full h-1.5 overflow-hidden">
        <div
          className="h-full rounded-full transition-all duration-100"
          style={{ width: `${progress}%`, background: color }}
        />
      </div>
      <p className="text-xs font-mono" style={{ color }}>
        {Math.round(progress)}%
      </p>
    </div>
  );
}

function ChatBubble({ text, isAgent = true, delay = 0, onVisible }) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => {
      setVisible(true);
      onVisible?.();
    }, delay);

    return () => clearTimeout(timer);
  }, [delay, onVisible]);

  if (!visible) {
    return null;
  }

  return (
    <div
      className={`flex gap-3 ${isAgent ? "justify-start" : "justify-end"}`}
      style={{ animation: "slideInUp 0.35s ease forwards" }}
    >
      {isAgent && (
        <div className="w-7 h-7 rounded-full bg-[#1f6feb] flex items-center justify-center flex-shrink-0 mt-1">
          <Icon name="Zap" size={12} className="text-white" />
        </div>
      )}
      <div
        className={`max-w-sm px-4 py-2.5 rounded-2xl text-sm leading-relaxed ${
          isAgent
            ? "bg-white border border-gray-200 text-gray-800 rounded-tl-sm shadow-sm"
            : "bg-[#1f6feb] text-white rounded-tr-sm"
        }`}
      >
        {text}
      </div>
    </div>
  );
}

function QuestionCard({ question, qIndex, total, onAnswer, delay = 0 }) {
  const [visible, setVisible] = useState(false);
  const [selected, setSelected] = useState(null);
  const [answered, setAnswered] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), delay);
    return () => clearTimeout(timer);
  }, [delay]);

  const handleSelect = (option) => {
    if (answered) {
      return;
    }

    setSelected(option);
    setAnswered(true);
    setTimeout(() => onAnswer(option), 600);
  };

  if (!visible) {
    return null;
  }

  return (
    <div style={{ animation: "slideInUp 0.4s ease forwards" }}>
      <div className="flex gap-3 mb-3">
        <div className="w-7 h-7 rounded-full bg-[#1f6feb] flex items-center justify-center flex-shrink-0 mt-1">
          <Icon name="Zap" size={12} className="text-white" />
        </div>
        <div className="bg-white border border-gray-200 rounded-2xl rounded-tl-sm px-4 py-3 max-w-sm shadow-sm">
          <p className="text-[10px] text-gray-400 mb-1">
            Question {qIndex + 1} of {total}
          </p>
          <p className="text-sm text-gray-800 leading-relaxed">{question.text}</p>
        </div>
      </div>

      {!answered && (
        <div className="ml-10 flex flex-wrap gap-2 mb-2" style={{ animation: "fadeIn 0.3s ease 0.2s both" }}>
          {question.options.map((option) => (
            <button
              key={option}
              onClick={() => handleSelect(option)}
              className="px-3 py-1.5 rounded-xl text-xs font-medium border transition-all duration-150 bg-white border-gray-200 text-gray-600 hover:border-[#1f6feb] hover:text-[#1f6feb] hover:bg-blue-50"
            >
              {option}
            </button>
          ))}
        </div>
      )}

      {answered && selected && (
        <div className="flex justify-end mb-2" style={{ animation: "slideInUp 0.3s ease forwards" }}>
          <div className="bg-[#1f6feb] text-white px-4 py-2 rounded-2xl rounded-tr-sm text-sm">
            {selected}
          </div>
        </div>
      )}
    </div>
  );
}

function SrsDocumentPanel({ onContinue }) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    setVisible(true);
    const timer = setTimeout(() => onContinue?.(), 5000);
    return () => clearTimeout(timer);
  }, [onContinue]);

  return (
    <div
      className={`w-full max-w-2xl transition-all duration-500 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}
    >
      <div className="flex items-center gap-3 mb-4 p-3 bg-blue-50 rounded-xl border border-blue-200">
        <Icon name="CheckCircle2" size={16} className="text-[#1f6feb]" />
        <p className="text-xs text-blue-700 font-medium">
          SRS generated successfully. Sending to Agent 2 Build Studio in 5 seconds...
        </p>
        <div className="ml-auto flex gap-1">
          {[0, 1, 2, 3, 4].map((dot) => (
            <div
              key={dot}
              className="w-1.5 h-1.5 rounded-full bg-[#1f6feb]"
              style={{ animation: `typingDot 1s ${dot * 0.2}s ease-in-out infinite` }}
            />
          ))}
        </div>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200 bg-gray-50">
          <div>
            <p className="text-sm font-bold text-gray-800">{SAMPLE_SRS.title}</p>
            <p className="text-xs text-gray-500 mt-0.5">{SAMPLE_SRS.version}</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#1f6feb] animate-pulse" />
            <span className="text-xs text-[#1f6feb]">Ready</span>
          </div>
        </div>
        <div className="p-5 space-y-4 max-h-80 overflow-y-auto">
          {SAMPLE_SRS.sections.map((section, index) => (
            <div key={section.heading} style={{ animation: `fadeIn 0.4s ease ${index * 0.15}s both` }}>
              <p className="text-xs font-semibold text-[#1f6feb] mb-1.5">{section.heading}</p>
              <p className="text-xs text-gray-600 leading-relaxed whitespace-pre-line">{section.body}</p>
              {index < SAMPLE_SRS.sections.length - 1 && <div className="mt-3 border-b border-gray-200" />}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function IdeaIntakeStage({ idea, onIdeaChange, onCreate }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-center p-8" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <div className="w-full max-w-xl">
        <div className="flex items-center gap-3 mb-8 justify-center">
          <img src="/logo.png" alt="AgentForge Studio logo" className="h-11 w-auto object-contain" />
          <div>
            <p className="text-sm font-bold text-gray-800">AgentForge Studio</p>
            <p className="text-xs text-gray-500">New Project Intake</p>
          </div>
        </div>

        <h1 className="text-3xl font-bold text-gray-800 text-center mb-2">What do you want to build?</h1>
        <p className="text-sm text-gray-500 text-center mb-8">
          Describe your software idea and our AI agents will handle the rest - from requirements to deployment.
        </p>

        <div className="relative">
          <textarea
            value={idea}
            onChange={(event) => onIdeaChange(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter" && event.metaKey) {
                onCreate();
              }
            }}
            placeholder="e.g. A hotel booking platform where guests can search rooms, make bookings, pay online, and hotel admins can manage inventory and view revenue reports..."
            rows={5}
            className="w-full bg-white border border-gray-300 rounded-2xl px-5 py-4 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:border-[#1f6feb] resize-none leading-relaxed transition-all"
            style={{ boxShadow: idea ? "0 0 0 1px #1f6feb30" : "none" }}
          />
          <div className="absolute bottom-3 right-3 text-[10px] text-gray-400">Cmd + Enter to create</div>
        </div>

        <button
          onClick={onCreate}
          disabled={!idea.trim()}
          className="w-full mt-4 py-3.5 rounded-xl text-sm font-semibold transition-all duration-200 flex items-center justify-center gap-2"
          style={{
            background: idea.trim() ? "#1f6feb" : "#e5e7eb",
            color: idea.trim() ? "white" : "#9ca3af",
            cursor: idea.trim() ? "pointer" : "not-allowed",
            boxShadow: idea.trim() ? "0 4px 20px #1f6feb40" : "none",
          }}
        >
          <Icon name="Zap" size={16} />
          Create Project with AI Agents
        </button>
      </div>
    </div>
  );
}

export function AnalysisStage({ idea, onComplete }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <div className="text-center mb-2">
        <p className="text-xs text-gray-400 mb-2">Reading your idea:</p>
        <p className="text-sm text-gray-600 max-w-sm italic">
          "{idea.length > 100 ? `${idea.slice(0, 100)}...` : idea}"
        </p>
      </div>
      <ProgressStagePanel
        label="Agent 1 is analyzing your idea..."
        duration={5}
        color="#1f6feb"
        statuses={[
          "Reading your idea...",
          "Extracting requirements...",
          "Identifying domain patterns...",
          "Mapping feature dependencies...",
          "Preparing 10 targeted questions...",
        ]}
        onComplete={onComplete}
      />
    </div>
  );
}

export function QuestioningStage({
  chatRef,
  currentQ,
  answers,
  onAnswer,
  showNextQ,
}) {
  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      <div className="flex items-center justify-between px-5 py-3 border-b border-gray-200 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-2 h-2 rounded-full bg-[#1f6feb] animate-pulse" />
          <p className="text-xs text-gray-600">Agent 1 - Requirement Gathering</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">
            {Math.min(currentQ + 1, QUESTIONS.length)} / {QUESTIONS.length} questions
          </span>
          <div className="w-24 bg-gray-200 rounded-full h-1 overflow-hidden">
            <div
              className="h-full bg-[#1f6feb] rounded-full transition-all duration-500"
              style={{ width: `${(answers.length / QUESTIONS.length) * 100}%` }}
            />
          </div>
        </div>
      </div>

      <div ref={chatRef} className="flex-1 overflow-y-auto px-6 py-6 space-y-4">
        <ChatBubble
          delay={0}
          text={`Great! I've read your idea. I have ${QUESTIONS.length} quick questions to build your perfect requirements. Let's start!`}
        />

        {Array.from({ length: Math.min(currentQ + 1, QUESTIONS.length) }).map((_, index) => (
          <QuestionCard
            key={QUESTIONS[index].id}
            question={QUESTIONS[index]}
            qIndex={index}
            total={QUESTIONS.length}
            onAnswer={index === currentQ ? onAnswer : () => {}}
            delay={index === currentQ && showNextQ ? 600 : 0}
          />
        ))}
      </div>
    </div>
  );
}

export function PreparingStage({ onComplete }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <div className="flex items-center gap-2 mb-2">
        <span className="w-2 h-2 rounded-full bg-[#1f6feb]" />
        <p className="text-xs text-[#1f6feb]">{QUESTIONS.length} / {QUESTIONS.length} questions answered</p>
      </div>
      <ProgressStagePanel
        label="Processing your answers..."
        duration={4}
        color="#1f6feb"
        statuses={[
          "Processing your answers...",
          "Building requirement clusters...",
          "Validating technical constraints...",
          "Finalizing project scope...",
        ]}
        onComplete={onComplete}
      />
    </div>
  );
}

export function GeneratingStage({ onComplete }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-center gap-6" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <ProgressStagePanel
        label="Generating Software Requirements Specification..."
        duration={10}
        color="#1f6feb"
        statuses={[
          "Structuring SRS document...",
          "Writing functional requirements...",
          "Generating non-functional specs...",
          "Defining data models...",
          "Mapping API contracts...",
          "Creating architecture diagram...",
          "Validating completeness...",
          "Running quality checks...",
          "Finalizing document...",
          "SRS ready.",
        ]}
        onComplete={onComplete}
      />
      <p className="text-xs text-gray-500 text-center max-w-xs">
        Agent 1 is structuring your SRS with functional requirements, architecture recommendations, and API contracts.
      </p>
    </div>
  );
}

export function GeneratedSrsStage({ onContinue }) {
  return (
    <div className="flex-1 flex flex-col items-center justify-start pt-8 px-6 overflow-y-auto" style={{ animation: "fadeIn 0.4s ease forwards" }}>
      <SrsDocumentPanel onContinue={onContinue} />
    </div>
  );
}
