"""
agents/kits.py — deterministic business-behaviour kits (never LLM).

Each kit adds fixed, parameterised TypeScript services + routes that implement the
error-prone server-side logic (atomic stock changes, invoice status derivation,
POS checkout, rental overlap, purchase receiving, sales) that a 12B model cannot
write bug-free. Kits are matched to the spec's data model + declared `kits` list.

The domain models themselves (SparePart, Invoice, …) are generated by the CRUD kit
from the SRS collections; these kits add the shared services + transaction endpoints
that operate on them.
"""
from __future__ import annotations

import json
import re


# ── model resolution (find the right collection by shape) ─────────────────────

def _model_names(spec: dict) -> list[str]:
    return [m.get("name", "") for m in (spec.get("data_model") or [])]


def _has_field(model: dict, name: str) -> bool:
    return any(f.get("name") == name for f in (model.get("fields") or []))


def find_model(spec: dict, *keywords: str, field: str | None = None) -> str | None:
    dm = spec.get("data_model") or []
    for m in dm:
        nm = str(m.get("name", "")).lower()
        if any(k in nm for k in keywords):
            return m["name"]
    if field:
        for m in dm:
            if _has_field(m, field):
                return m["name"]
    return None


# ── Inventory / Stock kit ─────────────────────────────────────────────────────

def _stock_lib(part: str, movement: str) -> str:
    return (
        f"import {part} from '@/models/{part}'\n"
        f"import {movement} from '@/models/{movement}'\n\n"
        "export interface StockChange {\n"
        "  sparePartId: string\n"
        "  quantity: number\n"
        "  movementType: string\n"
        "  direction: 1 | -1\n"
        "  referenceType?: string\n"
        "  referenceId?: string\n"
        "  note?: string\n"
        "  createdBy: string\n"
        "}\n\n"
        "// Atomic-ish stock change: validates non-negative stock, updates quantity, and\n"
        "// always writes a movement record. (Single-node in-memory Mongo has no multi-doc\n"
        "// transactions, so ops are sequential with a pre-check.)\n"
        "export async function adjustStock(c: StockChange): Promise<number> {\n"
        f"  const part: any = await {part}.findById(c.sparePartId)\n"
        "  if (!part) throw new Error('Item not found')\n"
        "  const before = Number(part.quantity || 0)\n"
        "  const after = before + c.direction * Math.abs(c.quantity)\n"
        "  if (after < 0) throw new Error('Insufficient stock')\n"
        "  part.quantity = after\n"
        "  await part.save()\n"
        f"  await {movement}.create({{\n"
        "    sparePartId: c.sparePartId, movementType: c.movementType,\n"
        "    quantity: Math.abs(c.quantity), quantityBefore: before, quantityAfter: after,\n"
        "    referenceType: c.referenceType || 'manual', referenceId: c.referenceId,\n"
        "    note: c.note, createdBy: c.createdBy,\n"
        "  })\n"
        "  return after\n"
        "}\n"
    )


_STOCK_ADJUST_ROUTE = (
    "import { NextRequest, NextResponse } from 'next/server'\n"
    "import dbConnect from '@/lib/mongodb'\n"
    "import { adjustStock } from '@/lib/stock'\n"
    "import { getSession } from '@/lib/auth'\n\n"
    "export const dynamic = 'force-dynamic'\n\n"
    "export async function POST(req: NextRequest) {\n"
    "  try {\n"
    "    const session = await getSession()\n"
    "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
    "    await dbConnect()\n"
    "    const body = await req.json()\n"
    "    const dir = body.direction === 'out' ? -1 : 1\n"
    "    const after = await adjustStock({\n"
    "      sparePartId: body.sparePartId, quantity: Number(body.quantity),\n"
    "      movementType: dir > 0 ? 'adjustment_in' : 'adjustment_out',\n"
    "      referenceType: 'manual', createdBy: session.userId, direction: dir as 1 | -1,\n"
    "    })\n"
    "    return NextResponse.json({ success: true, quantity: after })\n"
    "  } catch (e: any) {\n"
    "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
    "  }\n"
    "}\n"
)


def inventory_files(spec: dict) -> dict:
    part = find_model(spec, "sparepart", "part", "product", "item", field="reorderLevel") \
        or find_model(spec, "sparepart", "part", "product", field="quantity")
    movement = find_model(spec, "stockmovement", "movement")
    if not part or not movement:
        return {}
    return {
        "lib/stock.ts": _stock_lib(part, movement),
        "app/api/stock/adjust/route.ts": _STOCK_ADJUST_ROUTE,
    }


# ── Invoicing / Payments kit ──────────────────────────────────────────────────

def _invoicing_lib(invoice: str, payment: str) -> str:
    return (
        f"import {invoice} from '@/models/{invoice}'\n"
        f"import {payment} from '@/models/{payment}'\n\n"
        "export function invoiceStatus(total: number, paid: number): string {\n"
        "  if (paid <= 0) return 'unpaid'\n"
        "  if (paid >= total) return 'paid'\n"
        "  return 'partial'\n"
        "}\n\n"
        "export async function createInvoice(input: {\n"
        "  invoiceType: string; referenceId: string; customerId?: string;\n"
        "  subtotal: number; discount?: number; total: number;\n"
        "}) {\n"
        "  const discount = Number(input.discount || 0)\n"
        "  const total = Number(input.total)\n"
        f"  const inv = await {invoice}.create({{\n"
        "    invoiceNo: 'INV-' + Date.now(),\n"
        "    invoiceType: input.invoiceType, referenceId: input.referenceId,\n"
        "    customerId: input.customerId, subtotal: Number(input.subtotal),\n"
        "    discount, total, paidAmount: 0, balance: total, status: 'unpaid',\n"
        "    issuedAt: new Date(),\n"
        "  })\n"
        "  return inv\n"
        "}\n\n"
        "// Record a payment against an invoice. Server-side: amount>0, cannot exceed balance,\n"
        "// status recalculated. Never trusts client totals.\n"
        "export async function recordPayment(invoiceId: string, p: {\n"
        "  amount: number; method: string; reference?: string; receivedBy: string;\n"
        "}) {\n"
        f"  const inv: any = await {invoice}.findById(invoiceId)\n"
        "  if (!inv) throw new Error('Invoice not found')\n"
        "  const amount = Number(p.amount)\n"
        "  if (!(amount > 0)) throw new Error('Payment must be greater than zero')\n"
        "  const total = Number(inv.total || 0)\n"
        "  const newPaid = Number(inv.paidAmount || 0) + amount\n"
        "  if (newPaid > total) throw new Error('Payment exceeds invoice balance')\n"
        "  inv.paidAmount = newPaid\n"
        "  inv.balance = total - newPaid\n"
        "  inv.status = invoiceStatus(total, newPaid)\n"
        "  await inv.save()\n"
        f"  await {payment}.create({{\n"
        "    paymentNo: 'PAY-' + Date.now(), invoiceId, amount, method: p.method,\n"
        "    reference: p.reference, paidAt: new Date(), receivedBy: p.receivedBy,\n"
        "  })\n"
        "  return inv\n"
        "}\n"
    )


_INVOICE_PAYMENT_ROUTE = (
    "import { NextRequest, NextResponse } from 'next/server'\n"
    "import dbConnect from '@/lib/mongodb'\n"
    "import { recordPayment } from '@/lib/invoicing'\n"
    "import { getSession } from '@/lib/auth'\n\n"
    "export const dynamic = 'force-dynamic'\n\n"
    "export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n"
    "  try {\n"
    "    const { id } = await params\n"
    "    const session = await getSession()\n"
    "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
    "    await dbConnect()\n"
    "    const body = await req.json()\n"
    "    const inv = await recordPayment(id, {\n"
    "      amount: Number(body.amount), method: body.method || 'cash',\n"
    "      reference: body.reference, receivedBy: session.userId,\n"
    "    })\n"
    "    return NextResponse.json({ success: true, data: inv })\n"
    "  } catch (e: any) {\n"
    "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
    "  }\n"
    "}\n"
)


def invoicing_files(spec: dict) -> dict:
    invoice = find_model(spec, "invoice")
    payment = find_model(spec, "payment")
    if not invoice or not payment:
        return {}
    return {
        "lib/invoicing.ts": _invoicing_lib(invoice, payment),
        "app/api/invoices/[id]/payments/route.ts": _INVOICE_PAYMENT_ROUTE,
    }


# ── field helpers ─────────────────────────────────────────────────────────────

def _get_model(spec: dict, name: str) -> dict | None:
    return next((m for m in (spec.get("data_model") or []) if m.get("name") == name), None)


def find_field(model: dict | None, *names: str, ref: str | None = None,
               default: str | None = None) -> str | None:
    if not model:
        return default
    fields = model.get("fields") or []
    if ref:
        for f in fields:
            if f.get("ref") == ref:
                return f["name"]
    for f in fields:
        fn = str(f.get("name", "")).lower()
        if any(n in fn for n in names):
            return f["name"]
    return default


def _seg(name: str) -> str:
    from agents.scaffold import route_name
    return route_name(name)


# ── POS kit ───────────────────────────────────────────────────────────────────

def pos_files(spec: dict) -> dict:
    pos = find_model(spec, "possale", "pos")
    part = find_model(spec, "sparepart", "part", "product", field="reorderLevel") \
        or find_model(spec, "part", "product", field="quantity")
    has_invoicing = bool(find_model(spec, "invoice"))
    if not pos or not part:
        return {}
    inv_import = "import { createInvoice } from '@/lib/invoicing'\n" if has_invoicing else ""
    inv_block = (
        "    const invoice = await createInvoice({ invoiceType: 'pos', referenceId: String(sale._id), "
        "customerId: body.customerId, subtotal, discount, total })\n"
        "    invoice.paidAmount = total; invoice.balance = 0; invoice.status = 'paid'; await invoice.save()\n"
        "    return NextResponse.json({ success: true, data: { sale, invoice } })\n"
        if has_invoicing else
        "    return NextResponse.json({ success: true, data: { sale } })\n"
    )
    route = (
        "import { NextRequest, NextResponse } from 'next/server'\n"
        "import dbConnect from '@/lib/mongodb'\n"
        f"import {pos} from '@/models/{pos}'\n"
        f"import {part} from '@/models/{part}'\n"
        "import { adjustStock } from '@/lib/stock'\n"
        f"{inv_import}"
        "import { getSession } from '@/lib/auth'\n\n"
        "export const dynamic = 'force-dynamic'\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  try {\n"
        "    const session = await getSession()\n"
        "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
        "    await dbConnect()\n"
        "    const body = await req.json()\n"
        "    const items = Array.isArray(body.items) ? body.items : []\n"
        "    if (items.length === 0) throw new Error('Cart is empty')\n"
        "    const lineItems: any[] = []\n"
        "    let subtotal = 0\n"
        "    for (const it of items) {\n"
        f"      const p: any = await {part}.findById(it.sparePartId)\n"
        "      if (!p) throw new Error('Item not found')\n"
        "      const qty = Number(it.quantity)\n"
        "      if (!(qty >= 1)) throw new Error('Invalid quantity')\n"
        "      if (Number(p.quantity || 0) < qty) throw new Error('Insufficient stock for ' + p.name)\n"
        "      const unitPrice = Number(p.sellingPrice || 0)\n"
        "      const discount = Number(it.discount || 0)\n"
        "      const lineTotal = unitPrice * qty - discount\n"
        "      subtotal += lineTotal\n"
        "      lineItems.push({ sparePartId: p._id, partCode: p.partCode, name: p.name, quantity: qty, unitPrice, discount, lineTotal })\n"
        "    }\n"
        "    const discount = Number(body.discount || 0)\n"
        "    const total = subtotal - discount\n"
        "    for (const li of lineItems) {\n"
        "      await adjustStock({ sparePartId: String(li.sparePartId), quantity: li.quantity, movementType: 'pos_sale', direction: -1, referenceType: 'pos_sale', createdBy: session.userId })\n"
        "    }\n"
        f"    const sale = await {pos}.create({{ receiptNo: 'POS-' + Date.now(), customerId: body.customerId, items: lineItems, subtotal, discount, total, paymentMethod: body.paymentMethod || 'cash', paymentStatus: 'paid', createdBy: session.userId }})\n"
        f"{inv_block}"
        "  } catch (e: any) {\n"
        "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
        "  }\n"
        "}\n"
    )
    return {"app/api/pos/checkout/route.ts": route}


# ── Booking / Rental kit ──────────────────────────────────────────────────────

def booking_files(spec: dict) -> dict:
    rental = find_model(spec, "rental", "booking")
    vehicle = find_model(spec, "vehicle", "room", "resource", "asset")
    if not rental:
        return {}
    rm = _get_model(spec, rental)
    veh_field = find_field(rm, "vehicle", "room", "resource", "asset", ref=vehicle, default="vehicleId")
    # Detect the two date fields by TYPE (first = pickup/start, second = return/end) —
    # robust against ambiguous names (a "customer" field would falsely match "to").
    date_fields = [f["name"] for f in (rm.get("fields") or []) if str(f.get("type")) == "Date"]
    pickup = date_fields[0] if len(date_fields) >= 1 else "pickupAt"
    ret = date_fields[1] if len(date_fields) >= 2 else "returnAt"
    rate = find_field(rm, "dailyrate", "rate", default="dailyRate")
    fields = rm.get("fields") or []
    # Identifier (unique String) — auto-generate if the client omits it.
    id_field = next((f["name"] for f in fields if f.get("unique") and str(f.get("type")) == "String"), None)
    id_prefix = (re.sub(r"[^A-Za-z]", "", id_field)[:3].upper() if id_field else "BK") or "BK"
    # Optional derived fields — only set them if the model actually has them.
    days_field = next((f["name"] for f in fields if "day" in f["name"].lower() and str(f.get("type")) == "Number"), None)
    total_field = next((f["name"] for f in fields if f["name"].lower() in ("total", "grandtotal", "amount") and str(f.get("type")) == "Number"), None)
    status_enum = next((f.get("enum") for f in fields if f["name"] == "status"), None) or []
    _active = {"confirmed", "picked_up", "checked_in", "active", "booked", "borrowed", "reserved", "in_progress"}
    overlap = [s for s in status_enum if s in _active] or (["confirmed"] if not status_enum else [status_enum[0]])
    default_status = next((s for s in ["confirmed", "booked", "reserved", "requested"] if s in status_enum),
                          status_enum[0] if status_enum else "confirmed")
    overlap_ts = "[" + ", ".join(f"'{s}'" for s in overlap) + "]"
    create_parts = ["...body", f"{veh_field}: vehicleId", f"status: body.status || '{default_status}'"]
    if id_field:
        create_parts.append(f"{id_field}: body.{id_field} || '{id_prefix}-' + Date.now()")
    if days_field:
        create_parts.append(f"{days_field}: days")
    if total_field:
        create_parts.append(f"{total_field}: dailyRate * days")
    create_obj = "{ " + ", ".join(create_parts) + " }"
    seg = _seg(rental)
    route = (
        "import { NextRequest, NextResponse } from 'next/server'\n"
        "import dbConnect from '@/lib/mongodb'\n"
        f"import {rental} from '@/models/{rental}'\n"
        "import { ok, serverError } from '@/lib/api'\n"
        "import { getSession } from '@/lib/auth'\n\n"
        "export const dynamic = 'force-dynamic'\n\n"
        "export async function GET() {\n"
        "  try {\n"
        "    await dbConnect()\n"
        f"    const items = await {rental}.find({{}}).sort({{ createdAt: -1 }}).lean()\n"
        "    return ok(items)\n"
        "  } catch (e) { return serverError(e) }\n"
        "}\n\n"
        "export async function POST(req: NextRequest) {\n"
        "  try {\n"
        "    const session = await getSession()\n"
        "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
        "    await dbConnect()\n"
        "    const body = await req.json()\n"
        f"    const vehicleId = body.{veh_field}\n"
        f"    const pickup = new Date(body.{pickup})\n"
        f"    const ret = new Date(body.{ret})\n"
        "    if (isNaN(pickup.getTime()) || isNaN(ret.getTime())) throw new Error('Pickup and return dates are required')\n"
        "    if (ret <= pickup) throw new Error('Return date must be after pickup date')\n"
        "    // overlap: no active booking for this resource intersecting the range\n"
        f"    const clash = await {rental}.findOne({{\n"
        f"      {veh_field}: vehicleId, status: {{ $in: {overlap_ts} }},\n"
        f"      {pickup}: {{ $lt: ret }}, {ret}: {{ $gt: pickup }},\n"
        "    })\n"
        "    if (clash) return NextResponse.json({ error: 'Already booked for those dates' }, { status: 409 })\n"
        "    const days = Math.max(1, Math.ceil((ret.getTime() - pickup.getTime()) / 86400000))\n"
        f"    const dailyRate = Number(body.{rate} || 0)\n"
        f"    const item = await {rental}.create({create_obj})\n"
        "    return NextResponse.json({ success: true, data: item }, { status: 201 })\n"
        "  } catch (e: any) {\n"
        "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
        "  }\n"
        "}\n"
    )
    return {f"app/api/{seg}/route.ts": route}


# ── Sales kit ─────────────────────────────────────────────────────────────────

def sales_files(spec: dict) -> dict:
    sale = None
    for m in (spec.get("data_model") or []):
        nm = str(m.get("name", "")).lower()
        if "sale" in nm and "pos" not in nm:
            sale = m["name"]
            break
    vehicle = find_model(spec, "vehicle", "asset")
    has_invoicing = bool(find_model(spec, "invoice"))
    if not sale or not vehicle:
        return {}
    sm = _get_model(spec, sale)
    veh_field = find_field(sm, "vehicle", "asset", ref=vehicle, default="vehicleId")
    seg = _seg(sale)
    inv_import = "import { createInvoice } from '@/lib/invoicing'\n" if has_invoicing else ""
    inv_block = (
        "    const invoice = await createInvoice({ invoiceType: 'vehicle_sale', referenceId: String(item._id), customerId: body.customerId, subtotal: price, discount, total })\n"
        if has_invoicing else "")
    return {
        f"app/api/{seg}/route.ts": (
            "import { NextRequest, NextResponse } from 'next/server'\n"
            "import dbConnect from '@/lib/mongodb'\n"
            f"import {sale} from '@/models/{sale}'\n"
            f"import {vehicle} from '@/models/{vehicle}'\n"
            "import { ok, serverError } from '@/lib/api'\n"
            f"{inv_import}"
            "import { getSession } from '@/lib/auth'\n\n"
            "export const dynamic = 'force-dynamic'\n\n"
            "export async function GET() {\n"
            "  try {\n"
            "    await dbConnect()\n"
            f"    const items = await {sale}.find({{}}).sort({{ createdAt: -1 }}).lean()\n"
            "    return ok(items)\n"
            "  } catch (e) { return serverError(e) }\n"
            "}\n\n"
            "export async function POST(req: NextRequest) {\n"
            "  try {\n"
            "    const session = await getSession()\n"
            "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
            "    await dbConnect()\n"
            "    const body = await req.json()\n"
            f"    const veh: any = await {vehicle}.findById(body.{veh_field})\n"
            "    if (!veh) throw new Error('Vehicle not found')\n"
            "    if (veh.status === 'sold') throw new Error('Vehicle already sold')\n"
            "    const price = Number(body.price || veh.salePrice || 0)\n"
            "    const discount = Number(body.discount || 0)\n"
            "    const total = price - discount\n"
            f"    const item: any = await {sale}.create({{ ...body, price, discount, total, status: body.status || 'completed', saleNo: body.saleNo || 'SALE-' + Date.now(), officerId: session.userId, saleDate: body.saleDate || new Date() }})\n"
            "    veh.status = 'sold'; await veh.save()\n"
            f"{inv_block}"
            "    return NextResponse.json({ success: true, data: item }, { status: 201 })\n"
            "  } catch (e: any) {\n"
            "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
            "  }\n"
            "}\n"
        )
    }


# ── Workflow (job cards) kit ──────────────────────────────────────────────────

def workflow_files(spec: dict) -> dict:
    job = find_model(spec, "jobcard", "workorder", "ticket")
    part = find_model(spec, "sparepart", "part", "product", field="reorderLevel")
    if not job:
        return {}
    seg = _seg(job)
    stock_import = "import { adjustStock } from '@/lib/stock'\n" if part else ""
    stock_block = (
        "      if (item.itemType === 'spare_part' && item.sparePartId) {\n"
        "        await adjustStock({ sparePartId: String(item.sparePartId), quantity: Number(item.quantity || 1), movementType: 'service_usage', direction: -1, referenceType: 'job_card', referenceId: id, createdBy: session.userId })\n"
        "      }\n" if part else "")
    route = (
        "import { NextRequest, NextResponse } from 'next/server'\n"
        "import dbConnect from '@/lib/mongodb'\n"
        f"import {job} from '@/models/{job}'\n"
        f"{stock_import}"
        "import { getSession } from '@/lib/auth'\n\n"
        "export const dynamic = 'force-dynamic'\n\n"
        "export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {\n"
        "  try {\n"
        "    const { id } = await params\n"
        "    const session = await getSession()\n"
        "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
        "    await dbConnect()\n"
        f"    const card: any = await {job}.findById(id)\n"
        "    if (!card) return NextResponse.json({ error: 'Not found' }, { status: 404 })\n"
        "    const item = await req.json()\n"
        "    const quantity = Number(item.quantity || 1)\n"
        "    const unitPrice = Number(item.unitPrice || 0)\n"
        "    const lineTotal = quantity * unitPrice\n"
        f"{stock_block}"
        "    card.items = [...(card.items || []), { ...item, quantity, unitPrice, lineTotal }]\n"
        "    const labor = (card.items || []).filter((i: any) => i.itemType === 'labor').reduce((s: number, i: any) => s + Number(i.lineTotal || 0), 0)\n"
        "    const parts = (card.items || []).filter((i: any) => i.itemType === 'spare_part').reduce((s: number, i: any) => s + Number(i.lineTotal || 0), 0)\n"
        "    card.laborTotal = labor; card.partsTotal = parts; card.grandTotal = labor + parts\n"
        "    await card.save()\n"
        "    return NextResponse.json({ success: true, data: card })\n"
        "  } catch (e: any) {\n"
        "    return NextResponse.json({ error: e?.message || 'error' }, { status: 400 })\n"
        "  }\n"
        "}\n"
    )
    return {f"app/api/{seg}/[id]/items/route.ts": route}


# ── Dashboard / Reports kit ───────────────────────────────────────────────────

def reports_files(spec: dict) -> dict:
    dm = spec.get("data_model") or []
    if not dm:
        return {}
    invoice = find_model(spec, "invoice")
    part = find_model(spec, "sparepart", "part", "product", field="reorderLevel")
    imports = "".join(f"import {m['name']} from '@/models/{m['name']}'\n" for m in dm)
    counts = ",\n".join(f"      {json.dumps(_seg(m['name']))}: await {m['name']}.countDocuments()"
                        for m in dm)
    revenue = (f"    const paid = await {invoice}.find({{ status: 'paid' }}).lean()\n"
               f"    const revenue = paid.reduce((s: number, i: any) => s + Number(i.total || 0), 0)\n"
               if invoice else "    const revenue = 0\n")
    low = (f"    const lowStock = await {part}.countDocuments({{ $expr: {{ $lte: ['$quantity', '$reorderLevel'] }} }})\n"
           if part else "    const lowStock = 0\n")
    summary = (
        "import { NextResponse } from 'next/server'\n"
        "import dbConnect from '@/lib/mongodb'\n"
        f"{imports}"
        "import { getSession } from '@/lib/auth'\n\n"
        "export const dynamic = 'force-dynamic'\n\n"
        "export async function GET() {\n"
        "  try {\n"
        "    const session = await getSession()\n"
        "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
        "    await dbConnect()\n"
        "    const counts: Record<string, number> = {\n"
        f"{counts},\n"
        "    }\n"
        f"{revenue}"
        f"{low}"
        "    return NextResponse.json({ success: true, data: { counts, revenue, lowStock } })\n"
        "  } catch (e: any) {\n"
        "    return NextResponse.json({ error: e?.message || 'error' }, { status: 500 })\n"
        "  }\n"
        "}\n"
    )
    type_map: dict[str, str] = {}
    for m in dm:
        nm = m["name"].lower()
        if "possale" in nm or ("pos" in nm and "sale" in nm):
            type_map["pos"] = m["name"]
        elif "sale" in nm:
            type_map["sales"] = m["name"]
        elif "rental" in nm or "booking" in nm:
            type_map["rentals"] = m["name"]
        elif "invoice" in nm:
            type_map["invoices"] = m["name"]
    type_imports = "".join(f"import {v} from '@/models/{v}'\n" for v in dict.fromkeys(type_map.values()))
    cases = "\n".join(
        f"    if (type === '{k}') {{ const rows = await {v}.find(range).sort({{ createdAt: -1 }}).lean(); "
        f"const total = rows.reduce((s: number, r: any) => s + Number(r.total || 0), 0); "
        f"return NextResponse.json({{ success: true, data: {{ rows, total, count: rows.length }} }}) }}"
        for k, v in type_map.items()
    )
    reports = (
        "import { NextRequest, NextResponse } from 'next/server'\n"
        "import dbConnect from '@/lib/mongodb'\n"
        f"{type_imports}"
        "import { getSession } from '@/lib/auth'\n\n"
        "export const dynamic = 'force-dynamic'\n\n"
        "export async function GET(req: NextRequest) {\n"
        "  try {\n"
        "    const session = await getSession()\n"
        "    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n"
        "    await dbConnect()\n"
        "    const { searchParams } = new URL(req.url)\n"
        "    const type = searchParams.get('type') || ''\n"
        "    const from = searchParams.get('from'); const to = searchParams.get('to')\n"
        "    const range: any = {}\n"
        "    if (from || to) { range.createdAt = {}; if (from) range.createdAt.$gte = new Date(from); if (to) range.createdAt.$lte = new Date(to) }\n"
        f"{cases}\n"
        "    return NextResponse.json({ success: true, data: { rows: [], total: 0, count: 0 } })\n"
        "  } catch (e: any) {\n"
        "    return NextResponse.json({ error: e?.message || 'error' }, { status: 500 })\n"
        "  }\n"
        "}\n"
    )
    return {
        "app/api/dashboard/summary/route.ts": summary,
        "app/api/reports/route.ts": reports,
    }


# ── dispatcher ────────────────────────────────────────────────────────────────

def kit_files(spec: dict) -> dict:
    kits = set(spec.get("kits") or [])
    files: dict[str, str] = {}
    if "inventory" in kits:
        files.update(inventory_files(spec))
    if "invoicing" in kits:
        files.update(invoicing_files(spec))
    if "pos" in kits:
        files.update(pos_files(spec))
    if "booking" in kits:
        files.update(booking_files(spec))
    if "sales" in kits:
        files.update(sales_files(spec))
    if "workflow" in kits:
        files.update(workflow_files(spec))
    if "reports" in kits:
        files.update(reports_files(spec))
    return files
