import fs from "fs";
import path from "path";
import type { FinalReport } from "@/types";

type PDFDocument = PDFKit.PDFDocument;

export class PDFReporter {
  async generatePDF(report: FinalReport, _htmlPath: string, outputDir: string): Promise<string> {
    const pdfPath = path.join(outputDir, "pdf", "agent3_report.pdf");
    fs.mkdirSync(path.dirname(pdfPath), { recursive: true });

    try {
      const PDFKit = require("pdfkit") as typeof import("pdfkit");
      return this.generateWithPDFKit(report, pdfPath, PDFKit);
    } catch (err) {
      console.warn("[PDFReporter] PDFKit generation failed:", err);
      const fallback = path.join(outputDir, "pdf", "report_fallback.txt");
      fs.writeFileSync(fallback, this.generateTextFallback(report), "utf-8");
      return fallback;
    }
  }

  private generateWithPDFKit(
    report: FinalReport,
    outputPath: string,
    PDFKit: typeof import("pdfkit")
  ): Promise<string> {
    return new Promise((resolve, reject) => {
      const doc = new PDFKit({
        autoFirstPage: false,
        size: "A4",
        margin: 48,
        info: {
          Title: `Agent 3 QA Report - ${report.projectName}`,
          Author: "Agent 3 QA Platform",
          Subject: "QA Analysis Report",
          Keywords: "QA, PDF, report, Agent 3, IEEE-style",
        },
      });
      const stream = fs.createWriteStream(outputPath);
      let bodyStarted = false;
      let bodyPageNumber = 0;

      doc.pipe(stream);
      this.drawCoverPage(doc, report);

      doc.on("pageAdded", () => {
        if (!bodyStarted) return;
        bodyPageNumber += 1;
        this.drawPageChrome(doc, report, bodyPageNumber);
        doc.y = doc.page.margins.top + 28;
      });

      bodyStarted = true;
      doc.addPage({ margin: 48 });
      this.renderBody(doc, report);

      doc.end();
      stream.on("finish", () => resolve(outputPath));
      stream.on("error", reject);
    });
  }

  private drawCoverPage(doc: PDFDocument, report: FinalReport): void {
    doc.addPage({ margin: 0 });

    const width = doc.page.width;
    const height = doc.page.height;
    const qualityColor = report.qualityScore.passed ? "#15803d" : "#b91c1c";
    const gateLabel = report.qualityScore.passed ? "QUALITY GATE PASS" : "QUALITY GATE FAIL";

    doc.rect(0, 0, width, height).fill("#f4f7fb");
    doc.rect(0, 0, width, 180).fill("#0f172a");
    doc.rect(0, 180, width, 18).fill("#2563eb");
    doc.rect(0, height - 70, width, 70).fill("#0f172a");

    doc.fillColor("#e2e8f0").font("Helvetica-Bold").fontSize(11);
    doc.text("AGENT 3 QA PLATFORM", 56, 56);
    doc.font("Helvetica").fontSize(10).fillColor("#94a3b8");
    doc.text("Automated quality assurance analysis and traceability reporting", 56, 76);

    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(28);
    doc.text("Quality Assurance Report", 56, 250);
    doc.font("Helvetica").fontSize(14).fillColor("#334155");
    doc.text("IEEE-style assessment layout with actionable QA findings", 56, 288);

    doc.roundedRect(56, 340, width - 112, 128, 18).fill("#ffffff");
    doc.roundedRect(56, 340, width - 112, 128, 18).lineWidth(1).stroke("#cbd5e1");

    const metaLabelY = 366;
    const metaValueY = 390;
    const columnWidth = (width - 160) / 2;
    doc.fillColor("#64748b").font("Helvetica-Bold").fontSize(10);
    doc.text("PROJECT", 84, metaLabelY, { width: columnWidth });
    doc.text("STACK", 84 + columnWidth, metaLabelY, { width: columnWidth });
    doc.text("ANALYSIS DATE", 84, metaLabelY + 46, { width: columnWidth });
    doc.text("RUN ID", 84 + columnWidth, metaLabelY + 46, { width: columnWidth });

    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(15);
    doc.text(this.truncate(report.projectName, 28), 84, metaValueY, { width: columnWidth });
    doc.text(report.projectSummary.detectedStack, 84 + columnWidth, metaValueY, { width: columnWidth });
    doc.text(this.formatDate(report.analysisDate), 84, metaValueY + 46, { width: columnWidth });
    doc.text(this.truncate(report.runId, 28), 84 + columnWidth, metaValueY + 46, { width: columnWidth });

    doc.roundedRect(56, 500, width - 112, 78, 14).fill(qualityColor);
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(12);
    doc.text(gateLabel, 80, 522);
    doc.fontSize(24);
    doc.text(`${report.qualityScore.overall}/100`, 80, 542);
    doc.font("Helvetica").fontSize(11).fillColor("#dcfce7");
    doc.text(
      `${report.requirementsSummary.coveragePercent}% requirement coverage | ${report.securitySummary.total} security findings`,
      220,
      528,
      { width: width - 300 }
    );
    doc.text(
      `${report.unitTestSummary.passed}/${report.unitTestSummary.total} unit tests passed | ${report.integrationTestSummary.failed} integration failures`,
      220,
      548,
      { width: width - 300 }
    );

    doc.fillColor("#cbd5e1").font("Helvetica").fontSize(10);
    doc.text("Generated by Agent 3 for engineering review, risk triage, and release readiness.", 56, height - 44);
  }

  private renderBody(doc: PDFDocument, report: FinalReport): void {
    const abstract = [
      `${report.projectName} was analyzed across requirements coverage, automated verification,`,
      `code quality, security posture, and performance indicators.`,
      `The project achieved an overall QA score of ${report.qualityScore.overall}/100 with`,
      `${report.requirementsSummary.coveragePercent}% mapped requirement coverage.`,
      `This report is formatted as a structured engineering assessment so teams can identify`,
      `release blockers, validation gaps, and prioritized remediation work quickly.`,
    ].join(" ");

    this.drawSectionTitle(doc, "Abstract");
    this.drawParagraph(doc, abstract);
    this.drawCallout(
      doc,
      "Index Terms",
      [
        "quality assurance",
        "traceability",
        "unit testing",
        "integration testing",
        "security findings",
        "release readiness",
      ].join(", "),
      "#dbeafe",
      "#1d4ed8"
    );

    this.drawSectionTitle(doc, "1. Executive Overview");
    this.drawMetricCards(doc, [
      {
        label: "Overall QA Score",
        value: `${report.qualityScore.overall}/100`,
        subtext: report.qualityScore.passed ? "Quality gate passed" : "Quality gate failed",
        color: report.qualityScore.passed ? "#16a34a" : "#dc2626",
      },
      {
        label: "Requirement Coverage",
        value: `${report.requirementsSummary.coveragePercent}%`,
        subtext: `${report.requirementsSummary.implemented} implemented`,
        color: "#2563eb",
      },
      {
        label: "Security Findings",
        value: String(report.securitySummary.total),
        subtext: `${report.securitySummary.critical} critical`,
        color: report.securitySummary.critical > 0 ? "#dc2626" : "#0f766e",
      },
      {
        label: "Files Analyzed",
        value: String(report.projectSummary.totalFiles),
        subtext: this.truncate(report.projectSummary.frameworks.join(", ") || "Frameworks not detected", 34),
        color: "#7c3aed",
      },
    ]);

    this.drawTwoColumnFacts(doc, [
      ["Detected Stack", report.projectSummary.detectedStack],
      ["Frameworks", report.projectSummary.frameworks.join(", ") || "None detected"],
      ["TypeScript", report.projectSummary.hasTypeScript ? "Yes" : "No"],
      ["Python", report.projectSummary.hasPython ? "Yes" : "No"],
      ["Project Path", this.truncate(report.projectPath, 54)],
      ["SRS Path", this.truncate(report.srsPath, 54)],
    ]);

    this.drawSectionTitle(doc, "2. Requirements and Traceability");
    this.drawTable(
      doc,
      ["Metric", "Value", "Interpretation"],
      [
        ["Total Requirements", String(report.requirementsSummary.total), "All parsed functional and non-functional requirements"],
        ["Implemented", String(report.requirementsSummary.implemented), "Requirements with clear implementation evidence"],
        ["Partially Implemented", String(report.requirementsSummary.partiallyImplemented), "Requirements with incomplete coverage"],
        ["Missing", String(report.requirementsSummary.missing), "Requirements lacking implementation evidence"],
        ["Unverifiable", String(report.requirementsSummary.unverifiable), "Requirements needing stronger traceability"],
        ["Coverage", `${report.requirementsSummary.coveragePercent}%`, "Overall mapped implementation ratio"],
      ],
      [0.24, 0.16, 0.60]
    );

    this.drawSectionTitle(doc, "3. Verification Results");
    this.drawMetricCards(doc, [
      {
        label: "Unit Tests",
        value: String(report.unitTestSummary.total),
        subtext: `${report.unitTestSummary.passed} passed / ${report.unitTestSummary.failed} failed`,
        color: report.unitTestSummary.failed > 0 ? "#d97706" : "#16a34a",
      },
      {
        label: "Integration Tests",
        value: String(report.integrationTestSummary.total),
        subtext: `${report.integrationTestSummary.passed} passed / ${report.integrationTestSummary.failed} failed`,
        color: report.integrationTestSummary.failed > 0 ? "#dc2626" : "#0f766e",
      },
      {
        label: "Performance Alerts",
        value: String(report.performanceSummary.alerts),
        subtext: `${report.performanceSummary.total} findings recorded`,
        color: report.performanceSummary.alerts > 0 ? "#d97706" : "#2563eb",
      },
      {
        label: "Major Blockers",
        value: String(report.majorBlockers.length),
        subtext: report.majorBlockers.length > 0 ? "Needs engineering triage" : "No blocking items detected",
        color: report.majorBlockers.length > 0 ? "#dc2626" : "#16a34a",
      },
    ]);

    if (report.majorBlockers.length > 0) {
      this.drawListBlock(doc, "Critical QA Blockers", report.majorBlockers, "#fee2e2", "#b91c1c");
    } else {
      this.drawCallout(
        doc,
        "Blocking Status",
        "No major blockers were recorded in this analysis run.",
        "#dcfce7",
        "#15803d"
      );
    }

    this.drawSectionTitle(doc, "4. Quality Score Breakdown");
    this.drawScoreRow(doc, "Functional Correctness (40%)", report.qualityScore.functionalCorrectness);
    this.drawScoreRow(doc, "Code Quality (25%)", report.qualityScore.codeQuality);
    this.drawScoreRow(doc, "Security (20%)", report.qualityScore.security);
    this.drawScoreRow(doc, "Performance (15%)", report.qualityScore.performance);
    this.drawScoreRow(doc, "Overall Score", report.qualityScore.overall);

    this.drawSectionTitle(doc, "5. Security and Operational Risk");
    this.drawTable(
      doc,
      ["Category", "Count", "Status"],
      [
        ["Critical", String(report.securitySummary.critical), report.securitySummary.critical > 0 ? "Immediate remediation required" : "No critical items"],
        ["High", String(report.securitySummary.high), report.securitySummary.high > 0 ? "Prioritize before release" : "No high-severity items"],
        ["Medium", String(report.securitySummary.medium), report.securitySummary.medium > 0 ? "Schedule near-term fixes" : "No medium issues"],
        ["Low", String(report.securitySummary.low), report.securitySummary.low > 0 ? "Track as backlog improvements" : "No low issues"],
        ["Performance Alerts", String(report.performanceSummary.alerts), report.performanceSummary.alerts > 0 ? "Investigate throughput/latency impact" : "No active alerts"],
      ],
      [0.22, 0.16, 0.62]
    );

    this.drawSectionTitle(doc, "6. Recommendations");
    this.drawListBlock(
      doc,
      "Recommended Next Actions",
      report.recommendations.length > 0
        ? report.recommendations
        : ["No recommendations were generated for this run."],
      "#dbeafe",
      "#1d4ed8"
    );

    this.drawSectionTitle(doc, "7. Artifact Register");
    this.drawTable(
      doc,
      ["Artifact", "Type", "Notes"],
      report.artifacts.slice(0, 12).map((artifact) => [
        this.truncate(artifact, 34),
        artifact.split("/")[0] || "file",
        "Generated by the Agent 3 pipeline",
      ]),
      [0.46, 0.18, 0.36]
    );

    if (report.artifacts.length > 12) {
      this.drawCallout(
        doc,
        "Artifact Note",
        `${report.artifacts.length - 12} additional artifacts are available in the run output directory.`,
        "#fef3c7",
        "#b45309"
      );
    }
  }

  private drawPageChrome(doc: PDFDocument, report: FinalReport, pageNumber: number): void {
    const left = doc.page.margins.left;
    const right = doc.page.margins.right;
    const top = doc.page.margins.top;
    const bottom = doc.page.height - doc.page.margins.bottom + 8;
    const width = doc.page.width - left - right;

    doc.save();
    doc.lineWidth(1).strokeColor("#dbeafe");
    doc.moveTo(left, top - 14).lineTo(left + width, top - 14).stroke();
    doc.fillColor("#1e3a8a").font("Helvetica-Bold").fontSize(9);
    doc.text("Agent 3 QA Report", left, top - 30, { width: width / 2 });
    doc.fillColor("#475569").font("Helvetica").fontSize(8);
    doc.text(this.truncate(report.projectName, 40), left + width / 2, top - 30, {
      width: width / 2,
      align: "right",
    });

    doc.lineWidth(1).strokeColor("#e2e8f0");
    doc.moveTo(left, bottom).lineTo(left + width, bottom).stroke();
    doc.fillColor("#64748b").font("Helvetica").fontSize(8);
    doc.text(`Run ${this.truncate(report.runId, 16)} | Page ${pageNumber}`, left, bottom + 6, {
      width,
      align: "center",
    });
    doc.restore();
  }

  private drawSectionTitle(doc: PDFDocument, title: string): void {
    this.ensureSpace(doc, 50);
    doc.moveDown(0.3);
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const y = doc.y;
    doc.roundedRect(doc.page.margins.left, y, width, 28, 10).fill("#e0ecff");
    doc.fillColor("#1e3a8a").font("Helvetica-Bold").fontSize(13);
    doc.text(title, doc.page.margins.left + 14, y + 8, { width: width - 28 });
    doc.moveDown(1.9);
    doc.fillColor("#0f172a").font("Helvetica").fontSize(10.5);
  }

  private drawParagraph(doc: PDFDocument, text: string): void {
    this.ensureSpace(doc, 70);
    doc.fillColor("#334155").font("Helvetica").fontSize(10.5);
    doc.text(text, {
      width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      align: "justify",
      lineGap: 3,
    });
    doc.moveDown();
  }

  private drawCallout(
    doc: PDFDocument,
    label: string,
    text: string,
    background: string,
    accent: string
  ): void {
    const height = 54;
    this.ensureSpace(doc, height + 12);
    const x = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const y = doc.y;

    doc.roundedRect(x, y, width, height, 12).fill(background);
    doc.rect(x, y, 8, height).fill(accent);
    doc.fillColor(accent).font("Helvetica-Bold").fontSize(10);
    doc.text(label, x + 20, y + 10, { width: width - 32 });
    doc.fillColor("#0f172a").font("Helvetica").fontSize(10);
    doc.text(text, x + 20, y + 26, { width: width - 32 });
    doc.y = y + height + 10;
  }

  private drawMetricCards(
    doc: PDFDocument,
    cards: Array<{ label: string; value: string; subtext: string; color: string }>
  ): void {
    const x = doc.page.margins.left;
    const gap = 14;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const cardWidth = (width - gap) / 2;
    const cardHeight = 78;

    for (let index = 0; index < cards.length; index += 2) {
      this.ensureSpace(doc, cardHeight + 16);
      const rowY = doc.y;
      const row = cards.slice(index, index + 2);

      row.forEach((card, offset) => {
        const cardX = x + offset * (cardWidth + gap);
        doc.roundedRect(cardX, rowY, cardWidth, cardHeight, 14).fill("#ffffff");
        doc.roundedRect(cardX, rowY, cardWidth, cardHeight, 14).lineWidth(1).stroke("#dbe3f0");
        doc.roundedRect(cardX + 12, rowY + 12, 8, 54, 4).fill(card.color);

        doc.fillColor("#64748b").font("Helvetica-Bold").fontSize(9);
        doc.text(card.label.toUpperCase(), cardX + 30, rowY + 13, { width: cardWidth - 42 });
        doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(22);
        doc.text(card.value, cardX + 30, rowY + 31, { width: cardWidth - 42 });
        doc.fillColor("#475569").font("Helvetica").fontSize(9.5);
        doc.text(card.subtext, cardX + 30, rowY + 58, { width: cardWidth - 42 });
      });

      doc.y = rowY + cardHeight + 12;
    }
  }

  private drawTwoColumnFacts(doc: PDFDocument, rows: Array<[string, string]>): void {
    const left = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const columnWidth = (width - 18) / 2;
    const rowHeight = 38;

    for (let index = 0; index < rows.length; index += 2) {
      this.ensureSpace(doc, rowHeight + 10);
      const y = doc.y;
      const leftRow = rows[index];
      const rightRow = rows[index + 1];

      this.drawFactCell(doc, left, y, columnWidth, rowHeight, leftRow[0], leftRow[1]);
      if (rightRow) {
        this.drawFactCell(doc, left + columnWidth + 18, y, columnWidth, rowHeight, rightRow[0], rightRow[1]);
      }
      doc.y = y + rowHeight + 8;
    }
  }

  private drawFactCell(
    doc: PDFDocument,
    x: number,
    y: number,
    width: number,
    height: number,
    label: string,
    value: string
  ): void {
    doc.roundedRect(x, y, width, height, 10).fill("#f8fafc");
    doc.roundedRect(x, y, width, height, 10).lineWidth(1).stroke("#e2e8f0");
    doc.fillColor("#64748b").font("Helvetica-Bold").fontSize(8.5);
    doc.text(label.toUpperCase(), x + 12, y + 8, { width: width - 24 });
    doc.fillColor("#0f172a").font("Helvetica").fontSize(9.5);
    doc.text(value, x + 12, y + 20, { width: width - 24 });
  }

  private drawTable(
    doc: PDFDocument,
    headers: string[],
    rows: string[][],
    ratios: number[]
  ): void {
    const left = doc.page.margins.left;
    const totalWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const widths = ratios.map((ratio) => totalWidth * ratio);
    const headerHeight = 24;
    const rowHeight = 26;

    this.ensureSpace(doc, headerHeight + rowHeight * Math.min(rows.length, 6) + 18);
    let y = doc.y;

    doc.roundedRect(left, y, totalWidth, headerHeight, 8).fill("#1d4ed8");
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(9);
    let cursor = left;
    headers.forEach((header, index) => {
      doc.text(header, cursor + 10, y + 7, { width: widths[index] - 14 });
      cursor += widths[index];
    });
    y += headerHeight;

    rows.forEach((row, rowIndex) => {
      this.ensureSpace(doc, rowHeight + 6);
      if (y + rowHeight > doc.page.height - doc.page.margins.bottom - 20) {
        doc.addPage({ margin: 48 });
        y = doc.y;
        doc.roundedRect(left, y, totalWidth, headerHeight, 8).fill("#1d4ed8");
        doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(9);
        let headerCursor = left;
        headers.forEach((header, index) => {
          doc.text(header, headerCursor + 10, y + 7, { width: widths[index] - 14 });
          headerCursor += widths[index];
        });
        y += headerHeight;
      }

      doc.rect(left, y, totalWidth, rowHeight).fill(rowIndex % 2 === 0 ? "#f8fbff" : "#eef4ff");
      doc.rect(left, y, totalWidth, rowHeight).lineWidth(0.5).stroke("#dbeafe");
      doc.fillColor("#0f172a").font("Helvetica").fontSize(9);
      let cellX = left;
      row.forEach((cell, index) => {
        doc.text(this.truncate(cell, index === row.length - 1 ? 64 : 34), cellX + 10, y + 7, {
          width: widths[index] - 14,
        });
        cellX += widths[index];
      });
      y += rowHeight;
      doc.y = y;
    });

    doc.moveDown(0.6);
  }

  private drawScoreRow(doc: PDFDocument, label: string, value: number): void {
    this.ensureSpace(doc, 26);
    const left = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const y = doc.y;
    const barX = left + 190;
    const barWidth = width - 240;
    const scoreColor = value >= 80 ? "#16a34a" : value >= 60 ? "#d97706" : "#dc2626";

    doc.fillColor("#334155").font("Helvetica-Bold").fontSize(9.5);
    doc.text(label, left, y + 2, { width: 180 });

    doc.roundedRect(barX, y + 5, barWidth, 10, 5).fill("#e2e8f0");
    doc.roundedRect(barX, y + 5, Math.max(12, (barWidth * Math.max(value, 0)) / 100), 10, 5).fill(scoreColor);

    doc.fillColor(scoreColor).font("Helvetica-Bold").fontSize(10);
    doc.text(`${value}`, left + width - 36, y, { width: 36, align: "right" });
    doc.y = y + 22;
  }

  private drawListBlock(
    doc: PDFDocument,
    title: string,
    items: string[],
    background: string,
    accent: string
  ): void {
    const height = Math.max(54, 26 + items.length * 18);
    this.ensureSpace(doc, height + 12);
    const x = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const y = doc.y;

    doc.roundedRect(x, y, width, height, 14).fill(background);
    doc.roundedRect(x, y, width, height, 14).lineWidth(1).stroke("#e2e8f0");
    doc.fillColor(accent).font("Helvetica-Bold").fontSize(10);
    doc.text(title, x + 16, y + 12, { width: width - 32 });

    let itemY = y + 32;
    items.forEach((item) => {
      doc.fillColor(accent).font("Helvetica-Bold").fontSize(10);
      doc.text("-", x + 18, itemY, { width: 8 });
      doc.fillColor("#0f172a").font("Helvetica").fontSize(9.7);
      doc.text(item, x + 30, itemY, { width: width - 48 });
      itemY += 18;
    });

    doc.y = y + height + 10;
  }

  private ensureSpace(doc: PDFDocument, neededHeight: number): void {
    if (doc.y + neededHeight <= doc.page.height - doc.page.margins.bottom - 18) {
      return;
    }
    doc.addPage({ margin: 48 });
  }

  private formatDate(input: string): string {
    return new Date(input).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  }

  private truncate(value: string, maxLength: number): string {
    if (value.length <= maxLength) return value;
    return `${value.slice(0, Math.max(0, maxLength - 3))}...`;
  }

  private generateTextFallback(report: FinalReport): string {
    return [
      "=== AGENT 3 QA REPORT ===",
      `Project: ${report.projectName}`,
      `Date: ${report.analysisDate}`,
      `Quality Gate: ${report.qualityScore.passed ? "PASS" : "FAIL"}`,
      `Overall Score: ${report.qualityScore.overall}/100`,
      "",
      "=== REQUIREMENTS ===",
      `Total: ${report.requirementsSummary.total}`,
      `Coverage: ${report.requirementsSummary.coveragePercent}%`,
      `Missing: ${report.requirementsSummary.missing}`,
      "",
      "=== SECURITY ===",
      `Critical: ${report.securitySummary.critical}`,
      `High: ${report.securitySummary.high}`,
      `Total: ${report.securitySummary.total}`,
      "",
      "=== MAJOR BLOCKERS ===",
      ...report.majorBlockers.map((item) => `- ${item}`),
      "",
      "=== RECOMMENDATIONS ===",
      ...report.recommendations.map((item) => `- ${item}`),
    ].join("\n");
  }
}
